<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MechanicShop.Application\MechanicShop.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\Migrations\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.14.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="9.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.11" />
    <!--<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.9" />-->
    <!--<PackageReference Include="Microsoft.AspNetCore.Routing" Version="2.3.9" />-->
    <!--<PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.2.9" />-->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" Version="9.10.0" />
    <PackageReference Include="QuestPDF" Version="2025.12.2" />
    <!--<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.11" />-->
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="9.0.0" />
    <!--<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />-->
  </ItemGroup>

</Project>
